# Make nesting birds.

all:
	@echo "Making common..."
	@(cd common; make)
	@echo "Making mona..."
	@(cd mona; make)
	@echo "Making nestingbirds..."
	@(cd nestingbirds; make)
	@echo "done"

clean:
	(cd common; make clean)
	(cd mona; make clean)
	(cd nestingbirds; make clean)

