# Make nesting birds.

all:
	@echo "Making common..."
	@(cd src/common; make)
	@echo "Making mona..."
	@(cd src/mona; make)
	@echo "Making nestingbirds..."
	@(cd src/nestingbirds; make)
	@echo "done"

clean:
	(cd src/common; make clean)
	(cd src/mona; make clean)
	(cd src/nestingbirds; make clean)

